/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be in your git ignore file.
// It is autogenerated / managed by the env utility and is used to provide
// TypeScript completions for EXPO_PUBLIC_ environment variables.

declare namespace NodeJS {
  interface ProcessEnv {
    readonly EXPO_PUBLIC_API_BASE: string;
    readonly EXPO_PUBLIC_WS_URL: string;
    readonly EXPO_PUBLIC_OUTPUT_SAMPLE_RATE: string;
  }
}
